version: '3.8'

services:
  flask:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
  
  redis:
    image: redis
    volumes:
      - flashcardapp-redis-data:/data
  
  vue:
    build: ./frontend
    ports:
      - 8080:80

volumes:
  flashcardapp-redis-data:
